eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      ##enabled: true
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

  ## instance:
 ## hostname: localhost
