eureka:
  client:
#     register-with-eureka: true
#     fetch-registry: true
    serviceUrl:
      ##enabled: true
      defaultZone: http://service-registry:8761/eureka

  ## instance:
 ## hostname: localhost
