eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      enabled: true
      default-zone: http://cloud-config-server:8761/eureka

  instance:
    hostname: localhost
