eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      enabled: true
      ## uncomment for not using docker compose and comment the other one
      ## default-zone: http://localhost:8761/eureka
      default-zone: http://cloud-config-server:8761/eureka

  instance:
    hostname: localhost
